version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - static_volume:/service/static
      - media_volume:/service/media
    expose:
      - 8000  # Открываем порт для взаимодействия с nginx
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/service/static
    ports:
      - "8080:80"
    depends_on:
      - web-app

volumes:
  static_volume:
  media_volume:
  db_data:
